import { User } from './User.interface';

export interface SingleNFT {
  id: string;
  contract_address: string;
  asset_platform_id: string;
  name: string;
  symbol: string;
  image: Image;
  description: string;
  native_currency: string;
  native_currency_symbol: string;
  floor_price: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  market_cap: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  volume_24h: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  floor_price_in_usd_24h_percentage_change: number;
  floor_price_24h_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  market_cap_24h_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  volume_24h_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  number_of_unique_addresses: number;
  number_of_unique_addresses_24h_percentage_change: number;
  volume_in_usd_24h_percentage_change: number;
  total_supply: number;
  one_day_sales: number;
  one_day_sales_24h_percentage_change: number;
  one_day_average_sale_price: number;
  one_day_average_sale_price_24h_percentage_change: number;
  links: Links;
  floor_price_7d_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  floor_price_14d_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  floor_price_30d_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  floor_price_60d_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  floor_price_1y_percentage_change: FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange;
  explorers?: ExplorersEntity[] | null;
  collectionId?: number;
}
export interface Image {
  small: string;
}
export interface FloorPriceOrMarketCapOrVolume24hOrFloorPrice24hPercentageChangeOrMarketCap24hPercentageChangeOrVolume24hPercentageChangeOrFloorPrice7dPercentageChangeOrFloorPrice14dPercentageChangeOrFloorPrice30dPercentageChangeOrFloorPrice60dPercentageChangeOrFloorPrice1yPercentageChange {
  native_currency: number;
  usd: number;
}
export interface Links {
  homepage?: null;
  twitter: string;
  discord?: null;
}
export interface ExplorersEntity {
  name: string;
  link: string;
}

export interface NFTId {
  id?: number;
  nftid?: string;
  user?: User;
}
